/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Element
import org.openapitools.client.models.ImageElement
import org.openapitools.client.models.PanelElement
import org.openapitools.client.models.PanelGroupElement
import org.openapitools.client.models.TableElement
import org.openapitools.client.models.TextElement

class ElementTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Element
        //val modelInstance = Element()

        // to test the property `type` - The type of the included element object. The type also indicates which field contains the included element object. e.g. if the type is \"text\", the included element object will be in the \"text_element\" field.  Note that in the future, new type of element may be added, so your code should ignore unrecognized types, and unknown properties.  TODO: add Map type 
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `textElement`
        should("test textElement") {
            // uncomment below to test the property
            //modelInstance.textElement shouldBe ("TODO")
        }

        // to test the property `imageElement`
        should("test imageElement") {
            // uncomment below to test the property
            //modelInstance.imageElement shouldBe ("TODO")
        }

        // to test the property `actionElement`
        should("test actionElement") {
            // uncomment below to test the property
            //modelInstance.actionElement shouldBe ("TODO")
        }

        // to test the property `panelElement`
        should("test panelElement") {
            // uncomment below to test the property
            //modelInstance.panelElement shouldBe ("TODO")
        }

        // to test the property `panelGroupElement`
        should("test panelGroupElement") {
            // uncomment below to test the property
            //modelInstance.panelGroupElement shouldBe ("TODO")
        }

        // to test the property `tableElement`
        should("test tableElement") {
            // uncomment below to test the property
            //modelInstance.tableElement shouldBe ("TODO")
        }

    }
}
