/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustments
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsOriginsOfIngredients
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackaging
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsProductionSystem
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsThreatenedSpecies

class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustments
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustments()

        // to test the property `originsOfIngredients`
        should("test originsOfIngredients") {
            // uncomment below to test the property
            //modelInstance.originsOfIngredients shouldBe ("TODO")
        }

        // to test the property `packaging`
        should("test packaging") {
            // uncomment below to test the property
            //modelInstance.packaging shouldBe ("TODO")
        }

        // to test the property `productionSystem`
        should("test productionSystem") {
            // uncomment below to test the property
            //modelInstance.productionSystem shouldBe ("TODO")
        }

        // to test the property `threatenedSpecies`
        should("test threatenedSpecies") {
            // uncomment below to test the property
            //modelInstance.threatenedSpecies shouldBe ("TODO")
        }

    }
}
