/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackagingPackagingsInner

class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackagingPackagingsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackagingPackagingsInner
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackagingPackagingsInner()

        // to test the property `ecoscoreMaterialScore`
        should("test ecoscoreMaterialScore") {
            // uncomment below to test the property
            //modelInstance.ecoscoreMaterialScore shouldBe ("TODO")
        }

        // to test the property `ecoscoreShapeRatio`
        should("test ecoscoreShapeRatio") {
            // uncomment below to test the property
            //modelInstance.ecoscoreShapeRatio shouldBe ("TODO")
        }

        // to test the property `material`
        should("test material") {
            // uncomment below to test the property
            //modelInstance.material shouldBe ("TODO")
        }

        // to test the property `shape`
        should("test shape") {
            // uncomment below to test the property
            //modelInstance.shape shouldBe ("TODO")
        }

    }
}
