/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataPreviousData
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAgribalyse

class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataPreviousDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataPreviousData
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataPreviousData()

        // to test the property `grade`
        should("test grade") {
            // uncomment below to test the property
            //modelInstance.grade shouldBe ("TODO")
        }

        // to test the property `score`
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

        // to test the property `agribalyse`
        should("test agribalyse") {
            // uncomment below to test the property
            //modelInstance.agribalyse shouldBe ("TODO")
        }

    }
}
