/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfCategoriesProperties

class GetProductByBarcode200ResponseAllOfAllOfCategoriesPropertiesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfCategoriesProperties
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfCategoriesProperties()

        // to test the property `agribalyseFoodCodeColonEn`
        should("test agribalyseFoodCodeColonEn") {
            // uncomment below to test the property
            //modelInstance.agribalyseFoodCodeColonEn shouldBe ("TODO")
        }

        // to test the property `agribalyseProxyFoodCodeColonEn`
        should("test agribalyseProxyFoodCodeColonEn") {
            // uncomment below to test the property
            //modelInstance.agribalyseProxyFoodCodeColonEn shouldBe ("TODO")
        }

        // to test the property `ciqualFoodCodeColonEn`
        should("test ciqualFoodCodeColonEn") {
            // uncomment below to test the property
            //modelInstance.ciqualFoodCodeColonEn shouldBe ("TODO")
        }

    }
}
