/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfImages1SizesFull

class GetProductByBarcode200ResponseAllOfAllOfImages1SizesFullTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfImages1SizesFull
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfImages1SizesFull()

        // to test the property `h` - The height of the reduced/full image in pixels. 
        should("test h") {
            // uncomment below to test the property
            //modelInstance.h shouldBe ("TODO")
        }

        // to test the property `w` - The width of the reduced/full image in pixels.
        should("test w") {
            // uncomment below to test the property
            //modelInstance.w shouldBe ("TODO")
        }

    }
}
