/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfNutrientLevels

class GetProductByBarcode200ResponseAllOfAllOfNutrientLevelsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfNutrientLevels
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfNutrientLevels()

        // to test the property `fat`
        should("test fat") {
            // uncomment below to test the property
            //modelInstance.fat shouldBe ("TODO")
        }

        // to test the property `salt`
        should("test salt") {
            // uncomment below to test the property
            //modelInstance.salt shouldBe ("TODO")
        }

        // to test the property `saturatedFat`
        should("test saturatedFat") {
            // uncomment below to test the property
            //modelInstance.saturatedFat shouldBe ("TODO")
        }

        // to test the property `sugars`
        should("test sugars") {
            // uncomment below to test the property
            //modelInstance.sugars shouldBe ("TODO")
        }

    }
}
