/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfNovaGroupsMarkers

class GetProductByBarcode200ResponseAllOfAllOfNovaGroupsMarkersTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfNovaGroupsMarkers
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfNovaGroupsMarkers()

        // to test the property `_3` - Markers of level 3 
        should("test _3") {
            // uncomment below to test the property
            //modelInstance._3 shouldBe ("TODO")
        }

        // to test the property `_4` - Markers of level 4 
        should("test _4") {
            // uncomment below to test the property
            //modelInstance._4 shouldBe ("TODO")
        }

    }
}
