/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfImagesFront
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes

class GetProductByBarcode200ResponseAllOfAllOfImagesFrontTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfImagesFront
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfImagesFront()

        // to test the property `angle` - The angle of the image rotation (if it was rotated).
        should("test angle") {
            // uncomment below to test the property
            //modelInstance.angle shouldBe ("TODO")
        }

        // to test the property `coordinatesImageSize`
        should("test coordinatesImageSize") {
            // uncomment below to test the property
            //modelInstance.coordinatesImageSize shouldBe ("TODO")
        }

        // to test the property `geometry`
        should("test geometry") {
            // uncomment below to test the property
            //modelInstance.geometry shouldBe ("TODO")
        }

        // to test the property `imgid` - The id of the original/source image that was selected to edit(rotate, normalize etc) to produce this new image.
        should("test imgid") {
            // uncomment below to test the property
            //modelInstance.imgid shouldBe ("TODO")
        }

        // to test the property `normalize` - Normalize colors.
        should("test normalize") {
            // uncomment below to test the property
            //modelInstance.normalize shouldBe ("TODO")
        }

        // to test the property `rev`
        should("test rev") {
            // uncomment below to test the property
            //modelInstance.rev shouldBe ("TODO")
        }

        // to test the property `sizes`
        should("test sizes") {
            // uncomment below to test the property
            //modelInstance.sizes shouldBe ("TODO")
        }

        // to test the property `whiteMagic` - Photo on white background : Try to remove the background. 
        should("test whiteMagic") {
            // uncomment below to test the property
            //modelInstance.whiteMagic shouldBe ("TODO")
        }

        // to test the property `x1`
        should("test x1") {
            // uncomment below to test the property
            //modelInstance.x1 shouldBe ("TODO")
        }

        // to test the property `x2`
        should("test x2") {
            // uncomment below to test the property
            //modelInstance.x2 shouldBe ("TODO")
        }

        // to test the property `y1`
        should("test y1") {
            // uncomment below to test the property
            //modelInstance.y1 shouldBe ("TODO")
        }

        // to test the property `y2`
        should("test y2") {
            // uncomment below to test the property
            //modelInstance.y2 shouldBe ("TODO")
        }

    }
}
