/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissing

class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissing
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissing()

        // to test the property `labels`
        should("test labels") {
            // uncomment below to test the property
            //modelInstance.labels shouldBe ("TODO")
        }

        // to test the property `origins`
        should("test origins") {
            // uncomment below to test the property
            //modelInstance.origins shouldBe ("TODO")
        }

        // to test the property `packagings`
        should("test packagings") {
            // uncomment below to test the property
            //modelInstance.packagings shouldBe ("TODO")
        }

    }
}
