/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfSourcesFieldsOrgGs1

class GetProductByBarcode200ResponseAllOfAllOfSourcesFieldsOrgGs1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfSourcesFieldsOrgGs1
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfSourcesFieldsOrgGs1()

        // to test the property `gln`
        should("test gln") {
            // uncomment below to test the property
            //modelInstance.gln shouldBe ("TODO")
        }

        // to test the property `gpcCategoryCode`
        should("test gpcCategoryCode") {
            // uncomment below to test the property
            //modelInstance.gpcCategoryCode shouldBe ("TODO")
        }

        // to test the property `gpcCategoryName`
        should("test gpcCategoryName") {
            // uncomment below to test the property
            //modelInstance.gpcCategoryName shouldBe ("TODO")
        }

        // to test the property `isAllergenRelevantDataProvided`
        should("test isAllergenRelevantDataProvided") {
            // uncomment below to test the property
            //modelInstance.isAllergenRelevantDataProvided shouldBe ("TODO")
        }

        // to test the property `lastChangeDateTime`
        should("test lastChangeDateTime") {
            // uncomment below to test the property
            //modelInstance.lastChangeDateTime shouldBe ("TODO")
        }

        // to test the property `partyName`
        should("test partyName") {
            // uncomment below to test the property
            //modelInstance.partyName shouldBe ("TODO")
        }

        // to test the property `productionVariantDescription`
        should("test productionVariantDescription") {
            // uncomment below to test the property
            //modelInstance.productionVariantDescription shouldBe ("TODO")
        }

        // to test the property `publicationDateTime`
        should("test publicationDateTime") {
            // uncomment below to test the property
            //modelInstance.publicationDateTime shouldBe ("TODO")
        }

    }
}
