/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ImageElement

class ImageElementTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ImageElement
        //val modelInstance = ImageElement()

        // to test the property `url` - full URL of the image
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `width` - Width of the image.  This is just a suggestion coming from the server,  the client may choose to use its own dimensions for the image. 
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height` - Height of the image.  This is just a suggestion coming from the server, the client may choose to use its own dimensions for the image. 
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `altText` - Alt Text of the image.
        should("test altText") {
            // uncomment below to test the property
            //modelInstance.altText shouldBe ("TODO")
        }

    }
}
