/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Panels1
import org.openapitools.client.models.Panel

class Panels1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of Panels1
        //val modelInstance = Panels1()

        // to test the property `additionalProperties`
        should("test additionalProperties") {
            // uncomment below to test the property
            //modelInstance.additionalProperties shouldBe ("TODO")
        }

    }
}
