/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PatchApiV3ProductBarcodeRequest
import org.openapitools.client.models.ProductUpdateAPIV3WRITE

class PatchApiV3ProductBarcodeRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PatchApiV3ProductBarcodeRequest
        //val modelInstance = PatchApiV3ProductBarcodeRequest()

        // to test the property `lc` - 2 letter code of the language of the interface. Used for localizing some fields in returned values (e.g. knowledge panels). If not passed, the language may be inferred by the country of the user (passed through the cc field or inferred by the IP address).
        should("test lc") {
            // uncomment below to test the property
            //modelInstance.lc shouldBe ("TODO")
        }

        // to test the property `cc` - 2 letter code of the country of the user. Used for localizing some fields in returned values (e.g. knowledge panels). If not passed, the country may be inferred by the IP address of the request.
        should("test cc") {
            // uncomment below to test the property
            //modelInstance.cc shouldBe ("TODO")
        }

        // to test the property `fields` - Comma separated list of fields requested in the response. Special values: \"updated\": returns field that were updated by the query (e.g. sending \"packagings\" or \"packagings_add\" would return \"packagings\"), \"none\": returns no fields, \"all\": returns all fields except generated fields that need to be explicitly requested such as \"knowledge_panels\". Defaults to \"updated\" for WRITE requests, and \"all\" for READ requests.
        should("test fields") {
            // uncomment below to test the property
            //modelInstance.fields shouldBe ("TODO")
        }

        // to test the property `tagsLc` - 2 letter language code to request names of tags in a specific language.  For READ requets: if passed, all taxonomized tags of the response will include a lc_name property with the translation in the requested language, if available. Otherwise, the property value will contain the name in the original language, prefixed by the 2 language code and a colon.  For WRITE requests: if passed, taxonomized tags fields with a lc_name property will be considered to be in this language.
        should("test tagsLc") {
            // uncomment below to test the property
            //modelInstance.tagsLc shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `product`
        should("test product") {
            // uncomment below to test the property
            //modelInstance.product shouldBe ("TODO")
        }

    }
}
