/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ResponseStatusResult

class ResponseStatusResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseStatusResult
        //val modelInstance = ResponseStatusResult()

        // to test the property `id` - Identifier of a response result entry
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Name of the response result entry in English.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `lcName` - Name of the response result entry in the language specified in tags_lc, if supplied.
        should("test lcName") {
            // uncomment below to test the property
            //modelInstance.lcName shouldBe ("TODO")
        }

    }
}
