/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TableElement
import org.openapitools.client.models.TableElementColumnsInner

class TableElementTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TableElement
        //val modelInstance = TableElement()

        // to test the property `id` - An id for the table.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `title` - Title of the column. 
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `rows`
        should("test rows") {
            // uncomment below to test the property
            //modelInstance.rows shouldBe ("TODO")
        }

        // to test the property `columns`
        should("test columns") {
            // uncomment below to test the property
            //modelInstance.columns shouldBe ("TODO")
        }

    }
}
