/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TableElementColumnsInner

class TableElementColumnsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TableElementColumnsInner
        //val modelInstance = TableElementColumnsInner()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `text`
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

        // to test the property `textForSmallScreens`
        should("test textForSmallScreens") {
            // uncomment below to test the property
            //modelInstance.textForSmallScreens shouldBe ("TODO")
        }

        // to test the property `style`
        should("test style") {
            // uncomment below to test the property
            //modelInstance.style shouldBe ("TODO")
        }

        // to test the property `columnGroupId`
        should("test columnGroupId") {
            // uncomment below to test the property
            //modelInstance.columnGroupId shouldBe ("TODO")
        }

        // to test the property `shownByDefault`
        should("test shownByDefault") {
            // uncomment below to test the property
            //modelInstance.shownByDefault shouldBe ("TODO")
        }

    }
}
