/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TitleElement

class TitleElementTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TitleElement
        //val modelInstance = TitleElement()

        // to test the property `name` - A short name of this panel, not including any actual values
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `type` - Used to indicate how the value of this item is measured, such as \"grade\" for Nutri-Score and Eco-Score or \"percentage\" for Salt
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `grade` - The value for this panel where it corresponds to a A to E grade such as the Nutri-Score of the Eco-Score.
        should("test grade") {
            // uncomment below to test the property
            //modelInstance.grade shouldBe ("TODO")
        }

        // to test the property ``value`` - The numeric value of the panel, where the type is \"percentage\"
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `iconUrl`
        should("test iconUrl") {
            // uncomment below to test the property
            //modelInstance.iconUrl shouldBe ("TODO")
        }

        // to test the property `iconColorFromEvaluation`
        should("test iconColorFromEvaluation") {
            // uncomment below to test the property
            //modelInstance.iconColorFromEvaluation shouldBe ("TODO")
        }

        // to test the property `iconSize` - If set to \"small\", the icon should be displayed at a small size. 
        should("test iconSize") {
            // uncomment below to test the property
            //modelInstance.iconSize shouldBe ("TODO")
        }

    }
}
