/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WarningOrErrorMessageField

class WarningOrErrorMessageFieldTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WarningOrErrorMessageField
        //val modelInstance = WarningOrErrorMessageField()

        // to test the property `id` - Name of the field that triggered the warning or error.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property ``value`` - Value of the field that triggered the warning or error.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
