/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WarningOrErrorMessage
import org.openapitools.client.models.WarningOrErrorMessageField
import org.openapitools.client.models.WarningOrErrorMessageImpact
import org.openapitools.client.models.WarningOrErrorMessageMessage

class WarningOrErrorMessageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WarningOrErrorMessage
        //val modelInstance = WarningOrErrorMessage()

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property ``field``
        should("test `field`") {
            // uncomment below to test the property
            //modelInstance.`field` shouldBe ("TODO")
        }

        // to test the property `impact`
        should("test impact") {
            // uncomment below to test the property
            //modelInstance.impact shouldBe ("TODO")
        }

    }
}
