/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WarningOrErrorMessageImpact

class WarningOrErrorMessageImpactTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WarningOrErrorMessageImpact
        //val modelInstance = WarningOrErrorMessageImpact()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `lcName`
        should("test lcName") {
            // uncomment below to test the property
            //modelInstance.lcName shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `lcDescription`
        should("test lcDescription") {
            // uncomment below to test the property
            //modelInstance.lcDescription shouldBe ("TODO")
        }

    }
}
