/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.apis.ReadRequestsApi
import io.offscale.openfoodfacts.client.models.GetProductByBarcode200Response

class ReadRequestsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReadRequestsApi
        //val apiInstance = ReadRequestsApi()

        // to test getProductByBarcode
        should("test getProductByBarcode") {
            // uncomment below to test getProductByBarcode
            //val barcode : kotlin.String = 3017620422003 // kotlin.String | The barcode of the product to be fetched 
            //val cc : kotlin.String = us // kotlin.String | 2 letter code of the country of the user. Used for localizing some fields in returned values (e.g. knowledge panels). If not passed, the country may be inferred by the IP address of the request.
            //val lc : kotlin.String = fr // kotlin.String | 2 letter code of the language of the user. Used for localizing some fields in returned values (e.g. knowledge panels). If not passed, the language may be inferred by the Accept-Language header of the request.
            //val tagsLc : kotlin.String = tagsLc_example // kotlin.String | 2 letter language code to request names of tags in a specific language.  For READ requests: if passed, all taxonomized tags of the response will include a `lc_name` property with the translation in the requested language, if available. Otherwise, the property value will contain the name in the original language, prefixed by the 2 language code and a colon.
            //val fields : kotlin.String = fields_example // kotlin.String | Comma separated list of fields requested in the response.  Special values: * \"none\": returns no fields * \"raw\": returns all fields as stored internally in the database * \"all\": returns all fields except generated fields that need to be explicitly requested such as \"knowledge_panels\".  Defaults to \"all\" for READ requests. The \"all\" value can also be combined with fields like \"attribute_groups\" and \"knowledge_panels\".'
            //val knowledgePanelsIncluded : kotlin.String = health_card, environment_card // kotlin.String | When knowledge_panels are requested, you can specify which panels should be in the response. All the others will be excluded.
            //val knowledgePanelsExcluded : kotlin.String = health_card, environment_card // kotlin.String | When knowledge_panels are requested, you can specify which panels to exclude from the response. All the others will be included. If a panel is both excluded and included (with the knowledge_panels_excluded parameter), it will be excluded.
            //val result : GetProductByBarcode200Response = apiInstance.getProductByBarcode(barcode, cc, lc, tagsLc, fields, knowledgePanelsIncluded, knowledgePanelsExcluded)
            //result shouldBe ("TODO")
        }

    }
}
