/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.GetApiV3TagTagtypeTagOrTagid200ResponseAllOfTag
import io.offscale.openfoodfacts.client.models.Panels1

class GetApiV3TagTagtypeTagOrTagid200ResponseAllOfTagTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetApiV3TagTagtypeTagOrTagid200ResponseAllOfTag
        //val modelInstance = GetApiV3TagTagtypeTagOrTagid200ResponseAllOfTag()

        // to test the property `tagid` - Canonicalized tagid corresponding to the input tag_or_tagid
        should("test tagid") {
            // uncomment below to test the property
            //modelInstance.tagid shouldBe ("TODO")
        }

        // to test the property `tagtype` - Canonicalized tagtype
        should("test tagtype") {
            // uncomment below to test the property
            //modelInstance.tagtype shouldBe ("TODO")
        }

        // to test the property `knowledgePanels`
        should("test knowledgePanels") {
            // uncomment below to test the property
            //modelInstance.knowledgePanels shouldBe ("TODO")
        }

    }
}
