/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfSourcesFields
import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfSourcesFieldsOrgGs1

class GetProductByBarcode200ResponseAllOfAllOfSourcesFieldsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfSourcesFields
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfSourcesFields()

        // to test the property `orgGs1`
        should("test orgGs1") {
            // uncomment below to test the property
            //modelInstance.orgGs1 shouldBe ("TODO")
        }

    }
}
