/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes
import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100

class GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes()

        // to test the property `_100`
        should("test _100") {
            // uncomment below to test the property
            //modelInstance._100 shouldBe ("TODO")
        }

        // to test the property `_200`
        should("test _200") {
            // uncomment below to test the property
            //modelInstance._200 shouldBe ("TODO")
        }

        // to test the property `_400`
        should("test _400") {
            // uncomment below to test the property
            //modelInstance._400 shouldBe ("TODO")
        }

        // to test the property `full`
        should("test full") {
            // uncomment below to test the property
            //modelInstance.full shouldBe ("TODO")
        }

    }
}
