/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfImages1Sizes
import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfImages1SizesFull

class GetProductByBarcode200ResponseAllOfAllOfImages1SizesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfImages1Sizes
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfImages1Sizes()

        // to test the property `full`
        should("test full") {
            // uncomment below to test the property
            //modelInstance.full shouldBe ("TODO")
        }

    }
}
