/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfIngredientsAnalysis

class GetProductByBarcode200ResponseAllOfAllOfIngredientsAnalysisTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfIngredientsAnalysis
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfIngredientsAnalysis()

        // to test the property `enColonPalmOil`
        should("test enColonPalmOil") {
            // uncomment below to test the property
            //modelInstance.enColonPalmOil shouldBe ("TODO")
        }

        // to test the property `enColonVeganStatusUnknown`
        should("test enColonVeganStatusUnknown") {
            // uncomment below to test the property
            //modelInstance.enColonVeganStatusUnknown shouldBe ("TODO")
        }

        // to test the property `enColonVegetarianStatusUnknown`
        should("test enColonVegetarianStatusUnknown") {
            // uncomment below to test the property
            //modelInstance.enColonVegetarianStatusUnknown shouldBe ("TODO")
        }

    }
}
