/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100

class GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100()

        // to test the property `h` - The height of the reduced/full image in pixels. 
        should("test h") {
            // uncomment below to test the property
            //modelInstance.h shouldBe ("TODO")
        }

        // to test the property `w` - The width of the reduced/full image in pixels.
        should("test w") {
            // uncomment below to test the property
            //modelInstance.w shouldBe ("TODO")
        }

    }
}
