/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackaging
import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackagingPackagingsInner

class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackagingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackaging
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackaging()

        // to test the property `nonRecyclableAndNonBiodegradableMaterials`
        should("test nonRecyclableAndNonBiodegradableMaterials") {
            // uncomment below to test the property
            //modelInstance.nonRecyclableAndNonBiodegradableMaterials shouldBe ("TODO")
        }

        // to test the property `packagings`
        should("test packagings") {
            // uncomment below to test the property
            //modelInstance.packagings shouldBe ("TODO")
        }

        // to test the property `score`
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `warning`
        should("test warning") {
            // uncomment below to test the property
            //modelInstance.warning shouldBe ("TODO")
        }

    }
}
