/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfSelectedImagesFront

class GetProductByBarcode200ResponseAllOfAllOfSelectedImagesFrontTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfSelectedImagesFront
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfSelectedImagesFront()

        // to test the property `display` - Thumbnail urls of product image (front) adapted to display on product page 
        should("test display") {
            // uncomment below to test the property
            //modelInstance.display shouldBe ("TODO")
        }

        // to test the property `small` - Thumbnail urls of product image (front) adapted to display on product list page 
        should("test small") {
            // uncomment below to test the property
            //modelInstance.small shouldBe ("TODO")
        }

        // to test the property `thumb` - Thumbnail urls of product image (front) in smallest format 
        should("test thumb") {
            // uncomment below to test the property
            //modelInstance.thumb shouldBe ("TODO")
        }

    }
}
