/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfImages1
import io.offscale.openfoodfacts.client.models.GetProductByBarcode200ResponseAllOfAllOfImages1Sizes

class GetProductByBarcode200ResponseAllOfAllOfImages1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetProductByBarcode200ResponseAllOfAllOfImages1
        //val modelInstance = GetProductByBarcode200ResponseAllOfAllOfImages1()

        // to test the property `sizes`
        should("test sizes") {
            // uncomment below to test the property
            //modelInstance.sizes shouldBe ("TODO")
        }

        // to test the property `uploadedT` - The time the image was uploaded (as unix timestamp). 
        should("test uploadedT") {
            // uncomment below to test the property
            //modelInstance.uploadedT shouldBe ("TODO")
        }

        // to test the property `uploader` - The contributor that uploaded the image. 
        should("test uploader") {
            // uncomment below to test the property
            //modelInstance.uploader shouldBe ("TODO")
        }

    }
}
