/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.PackagingComponentWRITEWeightSpecified

class PackagingComponentWRITEWeightSpecifiedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PackagingComponentWRITEWeightSpecified
        //val modelInstance = PackagingComponentWRITEWeightSpecified()

    }
}
