/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.offscale.openfoodfacts.client.models.WarningOrErrorMessageMessage

class WarningOrErrorMessageMessageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WarningOrErrorMessageMessage
        //val modelInstance = WarningOrErrorMessageMessage()

        // to test the property `id` - Identifier of a response message. 
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Name of the response message entry in English.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `lcName` - Name of the response message entry in the language specified in tags_lc, if supplied.
        should("test lcName") {
            // uncomment below to test the property
            //modelInstance.lcName shouldBe ("TODO")
        }

        // to test the property `description` - Description of the problem specific to the request, in English.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `lcDescription` - Description of the problem specific to the request, in the language specified in tags_lc, if supplied.
        should("test lcDescription") {
            // uncomment below to test the property
            //modelInstance.lcDescription shouldBe ("TODO")
        }

    }
}
