/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import dev.upvote.api.models.ImageElement
import dev.upvote.api.models.PanelElement
import dev.upvote.api.models.PanelGroupElement
import dev.upvote.api.models.TableElement
import dev.upvote.api.models.TextElement

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Each element object contains one specific element object such as a text element or an image element. 
 *
 * @param type The type of the included element object. The type also indicates which field contains the included element object. e.g. if the type is \"text\", the included element object will be in the \"text_element\" field.  Note that in the future, new type of element may be added, so your code should ignore unrecognized types, and unknown properties.  TODO: add Map type 
 * @param textElement 
 * @param imageElement 
 * @param actionElement 
 * @param panelElement 
 * @param panelGroupElement 
 * @param tableElement 
 */

@Serializable
data class Element (

    /* The type of the included element object. The type also indicates which field contains the included element object. e.g. if the type is \"text\", the included element object will be in the \"text_element\" field.  Note that in the future, new type of element may be added, so your code should ignore unrecognized types, and unknown properties.  TODO: add Map type  */
    @SerialName("type")
    val type: Element.Type,

    @SerialName("text_element")
    val textElement: TextElement? = null,

    @SerialName("image_element")
    val imageElement: ImageElement? = null,

    @SerialName("action_element")
    val actionElement: kotlin.String? = null,

    @SerialName("panel_element")
    val panelElement: PanelElement? = null,

    @SerialName("panel_group_element")
    val panelGroupElement: PanelGroupElement? = null,

    @SerialName("table_element")
    val tableElement: TableElement? = null

) {

    /**
     * The type of the included element object. The type also indicates which field contains the included element object. e.g. if the type is \"text\", the included element object will be in the \"text_element\" field.  Note that in the future, new type of element may be added, so your code should ignore unrecognized types, and unknown properties.  TODO: add Map type 
     *
     * Values: text,image,action,panel,panel_group,table
     */
    // @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @SerialName("text") text("text"),
        @SerialName("image") image("image"),
        @SerialName("action") action("action"),
        @SerialName("panel") panel("panel"),
        @SerialName("panel_group") panel_group("panel_group"),
        @SerialName("table") table("table");
    }

}

