/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Panels1

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tagid Canonicalized tagid corresponding to the input tag_or_tagid
 * @param tagtype Canonicalized tagtype
 * @param knowledgePanels 
 */


data class GetApiV3TagTagtypeTagOrTagid200ResponseAllOfTag (

    /* Canonicalized tagid corresponding to the input tag_or_tagid */
    @Json(name = "tagid")
    val tagid: kotlin.String? = null,

    /* Canonicalized tagtype */
    @Json(name = "tagtype")
    val tagtype: kotlin.String? = null,

    @Json(name = "knowledge_panels")
    val knowledgePanels: Panels1? = null

) {


}

