/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetApiV3TagTagtypeTagOrTagid200ResponseAllOfTag
import org.openapitools.client.models.ResponseStatusResult
import org.openapitools.client.models.WarningOrErrorMessage

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param statusId Overall status of the request: whether it failed or succeeded, with or without warnings or errors.
 * @param result 
 * @param warnings List of warnings. Warnings are used to alert about something that may be wrong, but is not necessarily wrong (e.g. a nutrient value that is unexpectedly high).
 * @param errors List of errors. Errors are used to alert about something that is definitely wrong (e.g. a nutrient value thaty is impossibly high).
 * @param tagtype Input tagtype 
 * @param tagid Input tagid 
 * @param tag 
 */

@Serializable
data class GetApiV3TagTagtypeTagOrTagid200Response (

    /* Overall status of the request: whether it failed or succeeded, with or without warnings or errors. */
    @SerialName("status_id")
    val statusId: GetApiV3TagTagtypeTagOrTagid200Response.StatusId? = null,

    @SerialName("result")
    val result: ResponseStatusResult? = null,

    /* List of warnings. Warnings are used to alert about something that may be wrong, but is not necessarily wrong (e.g. a nutrient value that is unexpectedly high). */
    @SerialName("warnings")
    val warnings: kotlin.collections.List<WarningOrErrorMessage>? = null,

    /* List of errors. Errors are used to alert about something that is definitely wrong (e.g. a nutrient value thaty is impossibly high). */
    @SerialName("errors")
    val errors: kotlin.collections.List<WarningOrErrorMessage>? = null,

    /* Input tagtype  */
    @SerialName("tagtype")
    val tagtype: kotlin.String? = null,

    /* Input tagid  */
    @SerialName("tagid")
    val tagid: kotlin.String? = null,

    @SerialName("tag")
    val tag: GetApiV3TagTagtypeTagOrTagid200ResponseAllOfTag? = null

) {

    /**
     * Overall status of the request: whether it failed or succeeded, with or without warnings or errors.
     *
     * Values: success,success_with_warnings,success_with_errors,failure
     */
    // @JsonClass(generateAdapter = false)
    enum class StatusId(val value: kotlin.String) {
        @SerialName("success") success("success"),
        @SerialName("success_with_warnings") success_with_warnings("success_with_warnings"),
        @SerialName("success_with_errors") success_with_errors("success_with_errors"),
        @SerialName("failure") failure("failure");
    }

}

