/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import dev.upvote.api.models.Panels1

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param tagid Canonicalized tagid corresponding to the input tag_or_tagid
 * @param tagtype Canonicalized tagtype
 * @param knowledgePanels 
 */

@Serializable
data class GetApiV3TagTagtypeTagOrTagid200ResponseAllOfTag (

    /* Canonicalized tagid corresponding to the input tag_or_tagid */
    @SerialName("tagid")
    val tagid: kotlin.String? = null,

    /* Canonicalized tagtype */
    @SerialName("tagtype")
    val tagtype: kotlin.String? = null,

    @SerialName("knowledge_panels")
    val knowledgePanels: Panels1? = null

) {


}

