/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param agribalyseFoodCodeColonEn 
 * @param agribalyseProxyFoodCodeColonEn 
 * @param ciqualFoodCodeColonEn 
 */


data class GetProductByBarcode200ResponseAllOfAllOfCategoriesProperties (

    @Json(name = "agribalyse_food_code:en")
    val agribalyseFoodCodeColonEn: kotlin.String? = null,

    @Json(name = "agribalyse_proxy_food_code:en")
    val agribalyseProxyFoodCodeColonEn: kotlin.String? = null,

    @Json(name = "ciqual_food_code:en")
    val ciqualFoodCodeColonEn: kotlin.String? = null

) {


}

