/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsOriginsOfIngredients
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackaging
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsProductionSystem
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsThreatenedSpecies

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param originsOfIngredients 
 * @param packaging 
 * @param productionSystem 
 * @param threatenedSpecies 
 */


data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustments (

    @Json(name = "origins_of_ingredients")
    val originsOfIngredients: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsOriginsOfIngredients? = null,

    @Json(name = "packaging")
    val packaging: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackaging? = null,

    @Json(name = "production_system")
    val productionSystem: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsProductionSystem? = null,

    @Json(name = "threatened_species")
    val threatenedSpecies: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsThreatenedSpecies? = null

) {


}

