/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param labels 
 * @param origins 
 * @param packagings 
 */


data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissing (

    @Json(name = "labels")
    val labels: kotlin.Int? = null,

    @Json(name = "origins")
    val origins: kotlin.Int? = null,

    @Json(name = "packagings")
    val packagings: kotlin.Int? = null

) {


}

