/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfOwnerFieldsAdditionalProperties

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Those are fields provided by the producer (through producers platform), and the value he provided. 
 *
 * @param additionalProperties 
 */


data class GetProductByBarcode200ResponseAllOfAllOfOwnerFields (

    @Json(name = "additionalProperties")
    val additionalProperties: GetProductByBarcode200ResponseAllOfAllOfOwnerFieldsAdditionalProperties? = null

) {


}

