/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param h The height of the reduced/full image in pixels. 
 * @param w The width of the reduced/full image in pixels.
 */


data class GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100 (

    /* The height of the reduced/full image in pixels.  */
    @Json(name = "h")
    val h: kotlin.Int? = null,

    /* The width of the reduced/full image in pixels. */
    @Json(name = "w")
    val w: kotlin.Int? = null

) {


}

