/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param labels 
 * @param `value` 
 * @param warning 
 */


data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsProductionSystem (

    @Json(name = "labels")
    val labels: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "value")
    val `value`: kotlin.Int? = null,

    @Json(name = "warning")
    val warning: kotlin.String? = null

) {


}

