/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * properties of fullsize image **TODO** explain how to compute name 
 *
 * @param h The height of the reduced/full image in pixels. 
 * @param w The width of the reduced/full image in pixels.
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfImages1SizesFull (

    /* The height of the reduced/full image in pixels.  */
    @SerialName("h")
    val h: kotlin.Int? = null,

    /* The width of the reduced/full image in pixels. */
    @SerialName("w")
    val w: kotlin.Int? = null

) {


}

