/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import dev.upvote.api.models.GetProductByBarcode200ResponseAllOfAllOfImages1Sizes

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * This represents an image uploaded for this product. 
 *
 * @param sizes 
 * @param uploadedT The time the image was uploaded (as unix timestamp). 
 * @param uploader The contributor that uploaded the image. 
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfImages1 (

    @SerialName("sizes")
    val sizes: GetProductByBarcode200ResponseAllOfAllOfImages1Sizes? = null,

    /* The time the image was uploaded (as unix timestamp).  */
    @SerialName("uploaded_t")
    val uploadedT: kotlin.String? = null,

    /* The contributor that uploaded the image.  */
    @SerialName("uploader")
    val uploader: kotlin.String? = null

) {


}

