/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param enColonPalmOil 
 * @param enColonVeganStatusUnknown 
 * @param enColonVegetarianStatusUnknown 
 */


data class GetProductByBarcode200ResponseAllOfAllOfIngredientsAnalysis (

    @Json(name = "en:palm-oil")
    val enColonPalmOil: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "en:vegan-status-unknown")
    val enColonVeganStatusUnknown: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "en:vegetarian-status-unknown")
    val enColonVegetarianStatusUnknown: kotlin.collections.List<kotlin.String>? = null

) {


}

