/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * All known nutrients for the product.  Note that each nutrients are declined with a variety of suffixes like `_100g`, `_serving`, see patternProperties below.  A specific `_unit` is the unit used to measure the nutrient.  Beware that some properties are to be interpreted based upon `nutrition_data_per` value.  Also for products that have a nutrition table for prepared product (eg. the nutrition facts for a bowl of milk with cocoa powder), a `_prepared` suffix is added (before other suffixes).  You can get all possible nutrients from the [nutrients taxonomy](https://static.openfoodfacts.org/data/taxonomies/nutrients.json)  **FIXME** add more nutrients with description. 
 *
 * @param alcohol Quantity of alcohol  (per 100g or per serving) in a standard unit (g or ml) 
 * @param carbohydrates 
 * @param energy It is the same as `energy-kj` if we have it, or computed from `energy-kcal` otherwise  (per 100g or per serving) in kj 
 * @param energyValue energy_value will be equal to energy-kj_value if we have it or to energy-kcal_value otherwise 
 * @param energyUnit Equal to energy-kj_unit if we have it or to energy-kcal_unit otherwise 
 * @param energyKcal energy in kcal, if it is specified  (per 100g or per serving) in a standard unit (g or ml) 
 * @param energyKj energy in kj, if it is specified  (per 100g or per serving) in a standard unit (g or ml) 
 * @param fat 
 * @param fruitsVegetablesLegumesEstimateFromIngredients An estimate, from the ingredients list of the percentage of fruits, vegetable and legumes. This is an important information for Nutri-Score (2023 version) computation. 
 * @param fruitsVegetablesNutsEstimateFromIngredients An estimate, from the ingredients list of the percentage of fruits, vegetable and nuts. This is an important information for Nutri-Score (2021 version) computation. 
 * @param novaGroup 
 * @param nutritionScoreFr 
 * @param proteins 
 * @param salt 
 * @param saturatedFat 
 * @param sodium 
 * @param sugars 
 * @param carbonFootprintFromKnownIngredientsProduct 
 * @param carbonFootprintFromKnownIngredientsServing 
 * @param erythritol erythritol is a polyol which is not providing any energy. As such, it needs not be taken into account when computing the energy of a product. Eryhtritol is now displayed on nutrition facts sheet of some products, mainly in the USA. This value is entered either by contributors, either by imports. 
 */


data class GetProductByBarcode200ResponseAllOfAllOfNutriments (

    /* Quantity of alcohol  (per 100g or per serving) in a standard unit (g or ml)  */
    @Json(name = "alcohol")
    val alcohol: java.math.BigDecimal? = null,

    @Json(name = "carbohydrates")
    val carbohydrates: java.math.BigDecimal? = null,

    /* It is the same as `energy-kj` if we have it, or computed from `energy-kcal` otherwise  (per 100g or per serving) in kj  */
    @Json(name = "energy")
    val energy: java.math.BigDecimal? = null,

    /* energy_value will be equal to energy-kj_value if we have it or to energy-kcal_value otherwise  */
    @Json(name = "energy_value")
    val energyValue: java.math.BigDecimal? = null,

    /* Equal to energy-kj_unit if we have it or to energy-kcal_unit otherwise  */
    @Json(name = "energy_unit")
    val energyUnit: GetProductByBarcode200ResponseAllOfAllOfNutriments.EnergyUnit? = null,

    /* energy in kcal, if it is specified  (per 100g or per serving) in a standard unit (g or ml)  */
    @Json(name = "energy-kcal")
    val energyKcal: java.math.BigDecimal? = null,

    /* energy in kj, if it is specified  (per 100g or per serving) in a standard unit (g or ml)  */
    @Json(name = "energy-kj")
    val energyKj: java.math.BigDecimal? = null,

    @Json(name = "fat")
    val fat: java.math.BigDecimal? = null,

    /* An estimate, from the ingredients list of the percentage of fruits, vegetable and legumes. This is an important information for Nutri-Score (2023 version) computation.  */
    @Json(name = "fruits-vegetables-legumes-estimate-from-ingredients")
    val fruitsVegetablesLegumesEstimateFromIngredients: java.math.BigDecimal? = null,

    /* An estimate, from the ingredients list of the percentage of fruits, vegetable and nuts. This is an important information for Nutri-Score (2021 version) computation.  */
    @Json(name = "fruits-vegetables-nuts-estimate-from-ingredients")
    val fruitsVegetablesNutsEstimateFromIngredients: java.math.BigDecimal? = null,

    @Json(name = "nova-group")
    val novaGroup: kotlin.Int? = null,

    @Json(name = "nutrition-score-fr")
    val nutritionScoreFr: kotlin.Any? = null,

    @Json(name = "proteins")
    val proteins: java.math.BigDecimal? = null,

    @Json(name = "salt")
    val salt: java.math.BigDecimal? = null,

    @Json(name = "saturated-fat")
    val saturatedFat: java.math.BigDecimal? = null,

    @Json(name = "sodium")
    val sodium: java.math.BigDecimal? = null,

    @Json(name = "sugars")
    val sugars: java.math.BigDecimal? = null,

    @Json(name = "carbon-footprint-from-known-ingredients_product")
    val carbonFootprintFromKnownIngredientsProduct: kotlin.Int? = null,

    @Json(name = "carbon-footprint-from-known-ingredients_serving")
    val carbonFootprintFromKnownIngredientsServing: java.math.BigDecimal? = null,

    /* erythritol is a polyol which is not providing any energy. As such, it needs not be taken into account when computing the energy of a product. Eryhtritol is now displayed on nutrition facts sheet of some products, mainly in the USA. This value is entered either by contributors, either by imports.  */
    @Json(name = "erythritol")
    val erythritol: java.math.BigDecimal? = null

) {

    /**
     * Equal to energy-kj_unit if we have it or to energy-kcal_unit otherwise 
     *
     * Values: kcal,kj
     */
    @JsonClass(generateAdapter = false)
    enum class EnergyUnit(val value: kotlin.String) {
        @Json(name = "kcal") kcal("kcal"),
        @Json(name = "kj") kj("kj");
    }

}

