/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustments
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAgribalyse
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissing
import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataPreviousData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An object about a lot of details about data needed for Eco-Score computation  and complementary data of interest. 
 *
 * @param adjustments 
 * @param agribalyse 
 * @param grade 
 * @param grades 
 * @param missing 
 * @param missingDataWarning 
 * @param previousData 
 * @param score 
 * @param scores 
 * @param status 
 */


data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreData (

    @Json(name = "adjustments")
    val adjustments: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustments? = null,

    @Json(name = "agribalyse")
    val agribalyse: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAgribalyse? = null,

    @Json(name = "grade")
    val grade: kotlin.String? = null,

    @Json(name = "grades")
    val grades: kotlin.Any? = null,

    @Json(name = "missing")
    val missing: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissing? = null,

    @Json(name = "missing_data_warning")
    val missingDataWarning: kotlin.Int? = null,

    @Json(name = "previous_data")
    val previousData: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataPreviousData? = null,

    @Json(name = "score")
    val score: kotlin.Int? = null,

    @Json(name = "scores")
    val scores: kotlin.Any? = null,

    @Json(name = "status")
    val status: kotlin.String? = null

) {


}

