/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Detail of ingredients or processing that makes the products having Nova 3 or 4 
 *
 * @param _3 Markers of level 3 
 * @param _4 Markers of level 4 
 */


data class GetProductByBarcode200ResponseAllOfAllOfNovaGroupsMarkers (

    /* Markers of level 3  */
    @Json(name = "3")
    val _3: kotlin.collections.List<kotlin.collections.List<kotlin.String>>? = null,

    /* Markers of level 4  */
    @Json(name = "4")
    val _4: kotlin.collections.List<kotlin.collections.List<kotlin.String>>? = null

) {


}

