/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * 
 *
 * @param fields 
 * @param id 
 * @param images 
 * @param importT 
 * @param manufacturer 
 * @param name 
 * @param sourceLicence 
 * @param sourceLicenceUrl 
 * @param url 
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfSourcesInner (

    @SerialName("fields")
    val fields: kotlin.collections.List<kotlin.String>? = null,

    @SerialName("id")
    val id: kotlin.String? = null,

    @SerialName("images")
    val images: kotlin.collections.List<JsonElement>? = null,

    @SerialName("import_t")
    val importT: kotlin.Int? = null,

    @SerialName("manufacturer")
    val manufacturer: ByteArray? = null,

    @SerialName("name")
    val name: kotlin.String? = null,

    @SerialName("source_licence")
    val sourceLicence: kotlin.String? = null,

    @SerialName("source_licence_url")
    val sourceLicenceUrl: kotlin.String? = null,

    @SerialName("url")
    val url: kotlin.String? = null

) {


}

