/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * you can retrieve all kind of properties, the same as on the parent object (the product). It's not processed entries (like tags for example) but raw ones. 
 *
 */


data class GetProductByBarcode200ResponseAllOfAllOfOwnerFieldsAdditionalProperties (

) {


}

