/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Detail of data the Nutri-Score was computed upon.  **Note**: this might not be stable, don't rely too much on this, or, at least, tell us !  **TODO** document each property 
 *
 * @param energy 
 * @param energyPoints 
 * @param energyValue 
 * @param fiber 
 * @param fiberPoints 
 * @param fiberValue 
 * @param fruitsVegetablesNutsColzaWalnutOliveOils 
 * @param fruitsVegetablesNutsColzaWalnutOliveOilsPoints 
 * @param fruitsVegetablesNutsColzaWalnutOliveOilsValue 
 * @param grade 
 * @param isBeverage 
 * @param isCheese 
 * @param isFat 
 * @param isWater 
 * @param negativePoints 
 * @param positivePoints 
 * @param proteins 
 * @param proteinsPoints 
 * @param proteinsValue 
 * @param saturatedFat 
 * @param saturatedFatPoints 
 * @param saturatedFatRatio 
 * @param saturatedFatRatioPoints 
 * @param saturatedFatRatioValue 
 * @param saturatedFatValue 
 * @param score 
 * @param sodium 
 * @param sodiumPoints 
 * @param sodiumValue 
 * @param sugars 
 * @param sugarsPoints 
 * @param sugarsValue 
 */


data class GetProductByBarcode200ResponseAllOfAllOfNutriscoreData (

    @Json(name = "energy")
    val energy: kotlin.Int? = null,

    @Json(name = "energy_points")
    val energyPoints: kotlin.Int? = null,

    @Json(name = "energy_value")
    val energyValue: kotlin.Int? = null,

    @Json(name = "fiber")
    val fiber: kotlin.Int? = null,

    @Json(name = "fiber_points")
    val fiberPoints: kotlin.Int? = null,

    @Json(name = "fiber_value")
    val fiberValue: kotlin.Int? = null,

    @Json(name = "fruits_vegetables_nuts_colza_walnut_olive_oils")
    val fruitsVegetablesNutsColzaWalnutOliveOils: kotlin.Int? = null,

    @Json(name = "fruits_vegetables_nuts_colza_walnut_olive_oils_points")
    val fruitsVegetablesNutsColzaWalnutOliveOilsPoints: kotlin.Int? = null,

    @Json(name = "fruits_vegetables_nuts_colza_walnut_olive_oils_value")
    val fruitsVegetablesNutsColzaWalnutOliveOilsValue: kotlin.Int? = null,

    @Json(name = "grade")
    val grade: kotlin.String? = null,

    @Json(name = "is_beverage")
    val isBeverage: kotlin.Int? = null,

    @Json(name = "is_cheese")
    val isCheese: kotlin.Int? = null,

    @Json(name = "is_fat")
    val isFat: kotlin.Int? = null,

    @Json(name = "is_water")
    val isWater: kotlin.Int? = null,

    @Json(name = "negative_points")
    val negativePoints: kotlin.Int? = null,

    @Json(name = "positive_points")
    val positivePoints: kotlin.Int? = null,

    @Json(name = "proteins")
    val proteins: java.math.BigDecimal? = null,

    @Json(name = "proteins_points")
    val proteinsPoints: kotlin.Int? = null,

    @Json(name = "proteins_value")
    val proteinsValue: java.math.BigDecimal? = null,

    @Json(name = "saturated_fat")
    val saturatedFat: java.math.BigDecimal? = null,

    @Json(name = "saturated_fat_points")
    val saturatedFatPoints: kotlin.Int? = null,

    @Json(name = "saturated_fat_ratio")
    val saturatedFatRatio: java.math.BigDecimal? = null,

    @Json(name = "saturated_fat_ratio_points")
    val saturatedFatRatioPoints: kotlin.Int? = null,

    @Json(name = "saturated_fat_ratio_value")
    val saturatedFatRatioValue: java.math.BigDecimal? = null,

    @Json(name = "saturated_fat_value")
    val saturatedFatValue: java.math.BigDecimal? = null,

    @Json(name = "score")
    val score: kotlin.Int? = null,

    @Json(name = "sodium")
    val sodium: java.math.BigDecimal? = null,

    @Json(name = "sodium_points")
    val sodiumPoints: kotlin.Int? = null,

    @Json(name = "sodium_value")
    val sodiumValue: java.math.BigDecimal? = null,

    @Json(name = "sugars")
    val sugars: java.math.BigDecimal? = null,

    @Json(name = "sugars_points")
    val sugarsPoints: kotlin.Int? = null,

    @Json(name = "sugars_value")
    val sugarsValue: java.math.BigDecimal? = null

) {


}

