/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import dev.upvote.api.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustments
import dev.upvote.api.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAgribalyse
import dev.upvote.api.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissing
import dev.upvote.api.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataPreviousData

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An object about a lot of details about data needed for Eco-Score computation  and complementary data of interest. 
 *
 * @param adjustments 
 * @param agribalyse 
 * @param grade 
 * @param grades 
 * @param missing 
 * @param missingDataWarning 
 * @param previousData 
 * @param score 
 * @param scores 
 * @param status 
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreData (

    @SerialName("adjustments")
    val adjustments: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustments? = null,

    @SerialName("agribalyse")
    val agribalyse: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAgribalyse? = null,

    @SerialName("grade")
    val grade: kotlin.String? = null,

    @SerialName("grades")
    val grades: kotlin.Any? = null,

    @SerialName("missing")
    val missing: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissing? = null,

    @SerialName("missing_data_warning")
    val missingDataWarning: kotlin.Int? = null,

    @SerialName("previous_data")
    val previousData: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataPreviousData? = null,

    @SerialName("score")
    val score: kotlin.Int? = null,

    @SerialName("scores")
    val scores: kotlin.Any? = null,

    @SerialName("status")
    val status: kotlin.String? = null

) {


}

