/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfSourcesInnerManufacturer

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fields 
 * @param id 
 * @param images 
 * @param importT 
 * @param manufacturer 
 * @param name 
 * @param sourceLicence 
 * @param sourceLicenceUrl 
 * @param url 
 */


data class GetProductByBarcode200ResponseAllOfAllOfSourcesInner (

    @Json(name = "fields")
    val fields: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "images")
    val images: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "import_t")
    val importT: kotlin.Int? = null,

    @Json(name = "manufacturer")
    val manufacturer: GetProductByBarcode200ResponseAllOfAllOfSourcesInnerManufacturer? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "source_licence")
    val sourceLicence: kotlin.String? = null,

    @Json(name = "source_licence_url")
    val sourceLicenceUrl: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null

) {


}

