/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param ingredients Sub ingredients composing this ingredients. 
 * @param percent 
 * @param percentEstimate 
 * @param percentMax 
 * @param percentMin 
 * @param text 
 * @param vegan 
 * @param vegetarian 
 */


data class GetProductByBarcode200ResponseAllOfAllOfIngredientsInnerIngredientsInner (

    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Sub ingredients composing this ingredients.  */
    @Json(name = "ingredients")
    val ingredients: kotlin.Any? = null,

    @Json(name = "percent")
    val percent: kotlin.Int? = null,

    @Json(name = "percent_estimate")
    val percentEstimate: java.math.BigDecimal? = null,

    @Json(name = "percent_max")
    val percentMax: java.math.BigDecimal? = null,

    @Json(name = "percent_min")
    val percentMin: kotlin.Int? = null,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "vegan")
    val vegan: kotlin.String? = null,

    @Json(name = "vegetarian")
    val vegetarian: kotlin.String? = null

) {


}

