/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackagingPackagingsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param nonRecyclableAndNonBiodegradableMaterials 
 * @param packagings 
 * @param score 
 * @param `value` 
 * @param warning 
 */


data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackaging (

    @Json(name = "non_recyclable_and_non_biodegradable_materials")
    val nonRecyclableAndNonBiodegradableMaterials: kotlin.Int? = null,

    @Json(name = "packagings")
    val packagings: kotlin.collections.List<GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsPackagingPackagingsInner>? = null,

    @Json(name = "score")
    val score: kotlin.Int? = null,

    @Json(name = "value")
    val `value`: kotlin.Int? = null,

    @Json(name = "warning")
    val warning: kotlin.String? = null

) {


}

