/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAgribalyse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param grade 
 * @param score 
 * @param agribalyse 
 */


data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataPreviousData (

    @Json(name = "grade")
    val grade: kotlin.String? = null,

    @Json(name = "score")
    val score: kotlin.Int? = null,

    @Json(name = "agribalyse")
    val agribalyse: GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAgribalyse? = null

) {


}

