/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param agribalyseFoodCode 
 * @param co2Agriculture 
 * @param co2Consumption 
 * @param co2Distribution 
 * @param co2Packaging 
 * @param co2Processing 
 * @param co2Total 
 * @param co2Transportation 
 * @param code 
 * @param dqr 
 * @param efAgriculture 
 * @param efConsumption 
 * @param efDistribution 
 * @param efPackaging 
 * @param efProcessing 
 * @param efTotal 
 * @param efTransportation 
 * @param isBeverage 
 * @param nameEn This can be returned in many other languages like name_fr (for french). 
 * @param score 
 * @param version 
 */


data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAgribalyse (

    @Json(name = "agribalyse_food_code")
    val agribalyseFoodCode: kotlin.String? = null,

    @Json(name = "co2_agriculture")
    val co2Agriculture: java.math.BigDecimal? = null,

    @Json(name = "co2_consumption")
    val co2Consumption: kotlin.Int? = null,

    @Json(name = "co2_distribution")
    val co2Distribution: java.math.BigDecimal? = null,

    @Json(name = "co2_packaging")
    val co2Packaging: java.math.BigDecimal? = null,

    @Json(name = "co2_processing")
    val co2Processing: java.math.BigDecimal? = null,

    @Json(name = "co2_total")
    val co2Total: java.math.BigDecimal? = null,

    @Json(name = "co2_transportation")
    val co2Transportation: java.math.BigDecimal? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "dqr")
    val dqr: kotlin.String? = null,

    @Json(name = "ef_agriculture")
    val efAgriculture: java.math.BigDecimal? = null,

    @Json(name = "ef_consumption")
    val efConsumption: kotlin.Int? = null,

    @Json(name = "ef_distribution")
    val efDistribution: java.math.BigDecimal? = null,

    @Json(name = "ef_packaging")
    val efPackaging: java.math.BigDecimal? = null,

    @Json(name = "ef_processing")
    val efProcessing: java.math.BigDecimal? = null,

    @Json(name = "ef_total")
    val efTotal: java.math.BigDecimal? = null,

    @Json(name = "ef_transportation")
    val efTransportation: java.math.BigDecimal? = null,

    @Json(name = "is_beverage")
    val isBeverage: kotlin.Int? = null,

    /* This can be returned in many other languages like name_fr (for french).  */
    @Json(name = "name_en")
    val nameEn: kotlin.String? = null,

    @Json(name = "score")
    val score: kotlin.Int? = null,

    @Json(name = "version")
    val version: kotlin.String? = null

) {


}

