/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * This represents an image (or part of it) selected for a specific role on this product. 
 *
 * @param angle The angle of the image rotation (if it was rotated).
 * @param coordinatesImageSize 
 * @param geometry 
 * @param imgid The id of the original/source image that was selected to edit(rotate, normalize etc) to produce this new image.
 * @param normalize Normalize colors.
 * @param rev 
 * @param sizes 
 * @param whiteMagic Photo on white background : Try to remove the background. 
 * @param x1 
 * @param x2 
 * @param y1 
 * @param y2 
 */


data class GetProductByBarcode200ResponseAllOfAllOfImagesFront (

    /* The angle of the image rotation (if it was rotated). */
    @Json(name = "angle")
    val angle: kotlin.Int? = null,

    @Json(name = "coordinates_image_size")
    val coordinatesImageSize: kotlin.String? = null,

    @Json(name = "geometry")
    val geometry: kotlin.String? = null,

    /* The id of the original/source image that was selected to edit(rotate, normalize etc) to produce this new image. */
    @Json(name = "imgid")
    val imgid: kotlin.String? = null,

    /* Normalize colors. */
    @Json(name = "normalize")
    val normalize: kotlin.Any? = null,

    @Json(name = "rev")
    val rev: kotlin.String? = null,

    @Json(name = "sizes")
    val sizes: GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes? = null,

    /* Photo on white background : Try to remove the background.  */
    @Json(name = "white_magic")
    val whiteMagic: kotlin.Any? = null,

    @Json(name = "x1")
    val x1: kotlin.String? = null,

    @Json(name = "x2")
    val x2: kotlin.String? = null,

    @Json(name = "y1")
    val y1: kotlin.String? = null,

    @Json(name = "y2")
    val y2: kotlin.String? = null

) {


}

