/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import dev.upvote.api.models.GetProductByBarcode200ResponseAllOfAllOfSelectedImagesFront

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param front 
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfSelectedImages (

    @SerialName("front")
    val front: GetProductByBarcode200ResponseAllOfAllOfSelectedImagesFront? = null

) {


}

