/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * URLs of thumbnails image of image of type `image_type`
 *
 * @param display Thumbnail urls of product image (front) adapted to display on product page 
 * @param small Thumbnail urls of product image (front) adapted to display on product list page 
 * @param thumb Thumbnail urls of product image (front) in smallest format 
 */


data class GetProductByBarcode200ResponseAllOfAllOfSelectedImagesFront (

    /* Thumbnail urls of product image (front) adapted to display on product page  */
    @Json(name = "display")
    val display: kotlin.Any? = null,

    /* Thumbnail urls of product image (front) adapted to display on product list page  */
    @Json(name = "small")
    val small: kotlin.Any? = null,

    /* Thumbnail urls of product image (front) in smallest format  */
    @Json(name = "thumb")
    val thumb: kotlin.Any? = null

) {


}

