/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsOriginsOfIngredientsAggregatedOriginsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param aggregatedOrigins 
 * @param epiScore 
 * @param epiValue 
 * @param originsFromOriginsField 
 * @param transportationScores 
 * @param transportationValues 
 * @param propertyValues 
 * @param warning 
 */


data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsOriginsOfIngredients (

    @Json(name = "aggregated_origins")
    val aggregatedOrigins: kotlin.collections.List<GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsOriginsOfIngredientsAggregatedOriginsInner>? = null,

    @Json(name = "epi_score")
    val epiScore: kotlin.Int? = null,

    @Json(name = "epi_value")
    val epiValue: kotlin.Int? = null,

    @Json(name = "origins_from_origins_field")
    val originsFromOriginsField: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "transportation_scores")
    val transportationScores: kotlin.Any? = null,

    @Json(name = "transportation_values")
    val transportationValues: kotlin.Any? = null,

    @Json(name = "values")
    val propertyValues: kotlin.Any? = null,

    @Json(name = "warning")
    val warning: kotlin.String? = null

) {


}

