/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The available image sizes for the product (both reduced and full).  The reduced images are the ones with numbers as the key( 100, 200 etc) while the full images have `full` as the key. 
 *
 * @param _100 
 * @param _200 
 * @param _400 
 * @param full 
 */


data class GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes (

    @Json(name = "100")
    val _100: GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100? = null,

    @Json(name = "200")
    val _200: GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100? = null,

    @Json(name = "400")
    val _400: GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100? = null,

    @Json(name = "full")
    val full: GetProductByBarcode200ResponseAllOfAllOfImagesFrontSizes100? = null

) {


}

