/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param url full URL of the image
 * @param width Width of the image.  This is just a suggestion coming from the server,  the client may choose to use its own dimensions for the image. 
 * @param height Height of the image.  This is just a suggestion coming from the server, the client may choose to use its own dimensions for the image. 
 * @param altText Alt Text of the image.
 */


data class ImageElement (

    /* full URL of the image */
    @Json(name = "url")
    val url: kotlin.String? = null,

    /* Width of the image.  This is just a suggestion coming from the server,  the client may choose to use its own dimensions for the image.  */
    @Json(name = "width")
    val width: kotlin.Int? = null,

    /* Height of the image.  This is just a suggestion coming from the server, the client may choose to use its own dimensions for the image.  */
    @Json(name = "height")
    val height: kotlin.Int? = null,

    /* Alt Text of the image. */
    @Json(name = "alt_text")
    val altText: kotlin.String? = null

) {


}

