/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PackagingComponentMaterial
import org.openapitools.client.models.PackagingComponentRecyclingInstruction
import org.openapitools.client.models.PackagingComponentShape

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Each packaging component has different properties to specify how many there are, its shape, material etc.  The shape, material and recycling properties are mapped to one entry in the packaging_shapes, packaging_materials and packaging_recycling taxonomies, and the value of the property is the canonical name of the taxonomy entry (e.g. en:bottle).  They may contain values that could not yet get matched to their respective taxonomy, in which case they will contain a free text value prefixed with the language code of this text value (e.g. \"fr:Bouteille sphérique\" might have been entered by a French user to indicate it is a spherical bottle).
 *
 * @param numberOfUnits umber of units of this packaging component contained in the product (e.g. 6 for a pack of 6 bottles)
 * @param shape 
 * @param material 
 * @param recycling 
 * @param quantityPerUnit Quantity (weight or volume) of food product contained in the packaging component. (e.g. 75cl for a wine bottle)
 * @param quantityPerUnitValue Value parsed from the quantity field.
 * @param quantityPerUnitUnit Unit parsed and normalized from the quantity field.
 * @param weightSpecified Weight (as specified by the manufacturer) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component).
 * @param weightMeasured Weight (as measured by one or more users) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component).
 * @param weightEstimated Weight (as estimated from similar products) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component).
 * @param weight Weight of one unit of the empty packaging component.
 * @param weightSourceId Indicates which field was used to populate the \"weight\" field. Either \"specified\", \"measured\", or \"estimated\"
 */


data class PackagingComponentREAD (

    /* umber of units of this packaging component contained in the product (e.g. 6 for a pack of 6 bottles) */
    @Json(name = "number_of_units")
    val numberOfUnits: kotlin.Int? = null,

    @Json(name = "shape")
    val shape: PackagingComponentShape? = null,

    @Json(name = "material")
    val material: PackagingComponentMaterial? = null,

    @Json(name = "recycling")
    val recycling: PackagingComponentRecyclingInstruction? = null,

    /* Quantity (weight or volume) of food product contained in the packaging component. (e.g. 75cl for a wine bottle) */
    @Json(name = "quantity_per_unit")
    val quantityPerUnit: kotlin.String? = null,

    /* Value parsed from the quantity field. */
    @Json(name = "quantity_per_unit_value")
    val quantityPerUnitValue: java.math.BigDecimal? = null,

    /* Unit parsed and normalized from the quantity field. */
    @Json(name = "quantity_per_unit_unit")
    val quantityPerUnitUnit: kotlin.String? = null,

    /* Weight (as specified by the manufacturer) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component). */
    @Json(name = "weight_specified")
    val weightSpecified: java.math.BigDecimal? = null,

    /* Weight (as measured by one or more users) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component). */
    @Json(name = "weight_measured")
    val weightMeasured: java.math.BigDecimal? = null,

    /* Weight (as estimated from similar products) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component). */
    @Json(name = "weight_estimated")
    val weightEstimated: java.math.BigDecimal? = null,

    /* Weight of one unit of the empty packaging component. */
    @Json(name = "weight")
    val weight: java.math.BigDecimal? = null,

    /* Indicates which field was used to populate the \"weight\" field. Either \"specified\", \"measured\", or \"estimated\" */
    @Json(name = "weight_source_id")
    val weightSourceId: kotlin.String? = null

) {


}

