/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Element
import org.openapitools.client.models.TitleElement

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Each panel contains an optional title and an optional array of elements.
 *
 * @param type Type of the panel. If set to \"card\", the panel and its sub-panels should be displayed in a card. If set to \"inline\", the panel should have its content always displayed.
 * @param expanded If true, the panel is to be displayed already expanded. If false, only the title should be displayed, and the user should be able to click or tap it to open the panel and display the elements.
 * @param expandFor If set to \"large\", the content of the panel should be expanded on large screens, but it should still be possible to unexpand it.
 * @param evaluation A simple assessment of the panel value, typically used to format fonts, et.c e.g. bad = red
 * @param titleElement 
 * @param elements An ordered list of elements to display in the content of the panel.
 * @param level a message level, as levels we use in log. It might help theming the panel visualy 
 * @param propertySize size is either empty (normal display)  or small to indicate a panel that should have a smaller font size 
 * @param topics 
 */


data class Panel (

    /* Type of the panel. If set to \"card\", the panel and its sub-panels should be displayed in a card. If set to \"inline\", the panel should have its content always displayed. */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* If true, the panel is to be displayed already expanded. If false, only the title should be displayed, and the user should be able to click or tap it to open the panel and display the elements. */
    @Json(name = "expanded")
    val expanded: kotlin.Boolean? = null,

    /* If set to \"large\", the content of the panel should be expanded on large screens, but it should still be possible to unexpand it. */
    @Json(name = "expand_for")
    val expandFor: kotlin.String? = null,

    /* A simple assessment of the panel value, typically used to format fonts, et.c e.g. bad = red */
    @Json(name = "evaluation")
    val evaluation: Panel.Evaluation? = null,

    @Json(name = "title_element")
    val titleElement: TitleElement? = null,

    /* An ordered list of elements to display in the content of the panel. */
    @Json(name = "elements")
    val elements: kotlin.collections.List<Element>? = null,

    /* a message level, as levels we use in log. It might help theming the panel visualy  */
    @Json(name = "level")
    val level: kotlin.String? = null,

    /* size is either empty (normal display)  or small to indicate a panel that should have a smaller font size  */
    @Json(name = "size")
    val propertySize: Panel.PropertySize? = null,

    @Json(name = "topics")
    val topics: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * A simple assessment of the panel value, typically used to format fonts, et.c e.g. bad = red
     *
     * Values: good,average,neutral,bad,unknown
     */
    @JsonClass(generateAdapter = false)
    enum class Evaluation(val value: kotlin.String) {
        @Json(name = "good") good("good"),
        @Json(name = "average") average("average"),
        @Json(name = "neutral") neutral("neutral"),
        @Json(name = "bad") bad("bad"),
        @Json(name = "unknown") unknown("unknown");
    }
    /**
     * size is either empty (normal display)  or small to indicate a panel that should have a smaller font size 
     *
     * Values: small
     */
    @JsonClass(generateAdapter = false)
    enum class PropertySize(val value: kotlin.String) {
        @Json(name = "small") small("small");
    }

}

