/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param text 
 * @param textForSmallScreens 
 * @param style 
 * @param columnGroupId 
 * @param shownByDefault 
 */


data class TableElementColumnsInner (

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "text_for_small_screens")
    val textForSmallScreens: kotlin.String? = null,

    @Json(name = "style")
    val style: kotlin.String? = null,

    @Json(name = "column_group_id")
    val columnGroupId: kotlin.String? = null,

    @Json(name = "shown_by_default")
    val shownByDefault: kotlin.Boolean? = null

) {


}

