/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param id 
 * @param name 
 * @param lcName 
 * @param description 
 * @param lcDescription 
 */

@Serializable
data class WarningOrErrorMessageImpact (

    @SerialName("id")
    val id: kotlin.String? = null,

    @SerialName("name")
    val name: kotlin.String? = null,

    @SerialName("lc_name")
    val lcName: kotlin.String? = null,

    @SerialName("description")
    val description: kotlin.String? = null,

    @SerialName("lc_description")
    val lcDescription: kotlin.String? = null

) {


}

