/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param id Identifier of a response message. 
 * @param name Name of the response message entry in English.
 * @param lcName Name of the response message entry in the language specified in tags_lc, if supplied.
 * @param description Description of the problem specific to the request, in English.
 * @param lcDescription Description of the problem specific to the request, in the language specified in tags_lc, if supplied.
 */

@Serializable
data class WarningOrErrorMessageMessage (

    /* Identifier of a response message.  */
    @SerialName("id")
    val id: kotlin.String? = null,

    /* Name of the response message entry in English. */
    @SerialName("name")
    val name: kotlin.String? = null,

    /* Name of the response message entry in the language specified in tags_lc, if supplied. */
    @SerialName("lc_name")
    val lcName: kotlin.String? = null,

    /* Description of the problem specific to the request, in English. */
    @SerialName("description")
    val description: kotlin.String? = null,

    /* Description of the problem specific to the request, in the language specified in tags_lc, if supplied. */
    @SerialName("lc_description")
    val lcDescription: kotlin.String? = null

) {


}

