/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Field that triggered the warning or error.
 *
 * @param id Name of the field that triggered the warning or error.
 * @param `value` Value of the field that triggered the warning or error.
 */


data class WarningOrErrorMessageField (

    /* Name of the field that triggered the warning or error. */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Value of the field that triggered the warning or error. */
    @Json(name = "value")
    val `value`: kotlin.String? = null

) {


}

