/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WarningOrErrorMessageField
import org.openapitools.client.models.WarningOrErrorMessageImpact
import org.openapitools.client.models.WarningOrErrorMessageMessage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Describes a warning or error for a READ or WRITE request, which field triggered it, and what the impact was (e.g. the field was ignored).
 *
 * @param message 
 * @param `field` 
 * @param impact 
 */


data class WarningOrErrorMessage (

    @Json(name = "message")
    val message: WarningOrErrorMessageMessage? = null,

    @Json(name = "field")
    val `field`: WarningOrErrorMessageField? = null,

    @Json(name = "impact")
    val impact: WarningOrErrorMessageImpact? = null

) {


}

