/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Field that triggered the warning or error.
 *
 * @param id Name of the field that triggered the warning or error.
 * @param `value` Value of the field that triggered the warning or error.
 */

@Serializable
data class WarningOrErrorMessageField (

    /* Name of the field that triggered the warning or error. */
    @SerialName("id")
    val id: kotlin.String? = null,

    /* Value of the field that triggered the warning or error. */
    @SerialName("value")
    val `value`: kotlin.String? = null

) {


}

