/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Identifier of a response message. 
 * @param name Name of the response message entry in English.
 * @param lcName Name of the response message entry in the language specified in tags_lc, if supplied.
 * @param description Description of the problem specific to the request, in English.
 * @param lcDescription Description of the problem specific to the request, in the language specified in tags_lc, if supplied.
 */


data class WarningOrErrorMessageMessage (

    /* Identifier of a response message.  */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Name of the response message entry in English. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Name of the response message entry in the language specified in tags_lc, if supplied. */
    @Json(name = "lc_name")
    val lcName: kotlin.String? = null,

    /* Description of the problem specific to the request, in English. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Description of the problem specific to the request, in the language specified in tags_lc, if supplied. */
    @Json(name = "lc_description")
    val lcDescription: kotlin.String? = null

) {


}

