/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Detail of ingredients or processing that makes the products having Nova 3 or 4 
 *
 * @param _3 Markers of level 3 
 * @param _4 Markers of level 4 
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfNovaGroupsMarkers (

    /* Markers of level 3  */
    @SerialName("3")
    val _3: kotlin.collections.List<kotlin.collections.List<kotlin.String>>? = null,

    /* Markers of level 4  */
    @SerialName("4")
    val _4: kotlin.collections.List<kotlin.collections.List<kotlin.String>>? = null

) {


}

