/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param agribalyseFoodCodeColonEn 
 * @param agribalyseProxyFoodCodeColonEn 
 * @param ciqualFoodCodeColonEn 
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfCategoriesProperties (

    @SerialName("agribalyse_food_code:en")
    val agribalyseFoodCodeColonEn: kotlin.String? = null,

    @SerialName("agribalyse_proxy_food_code:en")
    val agribalyseProxyFoodCodeColonEn: kotlin.String? = null,

    @SerialName("ciqual_food_code:en")
    val ciqualFoodCodeColonEn: kotlin.String? = null

) {


}

