/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param gln 
 * @param gpcCategoryCode 
 * @param gpcCategoryName 
 * @param isAllergenRelevantDataProvided 
 * @param lastChangeDateTime 
 * @param partyName 
 * @param productionVariantDescription 
 * @param publicationDateTime 
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfSourcesFieldsOrgGs1 (

    @SerialName("gln")
    val gln: kotlin.String? = null,

    @SerialName("gpcCategoryCode")
    val gpcCategoryCode: kotlin.String? = null,

    @SerialName("gpcCategoryName")
    val gpcCategoryName: kotlin.String? = null,

    @SerialName("isAllergenRelevantDataProvided")
    val isAllergenRelevantDataProvided: kotlin.String? = null,

    @SerialName("lastChangeDateTime")
    val lastChangeDateTime: kotlin.String? = null,

    @SerialName("partyName")
    val partyName: kotlin.String? = null,

    @SerialName("productionVariantDescription")
    val productionVariantDescription: kotlin.String? = null,

    @SerialName("publicationDateTime")
    val publicationDateTime: kotlin.String? = null

) {


}

