/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param labels 
 * @param `value` 
 * @param warning 
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataAdjustmentsProductionSystem (

    @SerialName("labels")
    val labels: kotlin.collections.List<kotlin.String>? = null,

    @SerialName("value")
    val `value`: kotlin.Int? = null,

    @SerialName("warning")
    val warning: kotlin.String? = null

) {


}

