/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param labels 
 * @param origins 
 * @param packagings 
 */

@Serializable
data class GetProductByBarcode200ResponseAllOfAllOfEcoscoreDataMissing (

    @SerialName("labels")
    val labels: kotlin.Int? = null,

    @SerialName("origins")
    val origins: kotlin.Int? = null,

    @SerialName("packagings")
    val packagings: kotlin.Int? = null

) {


}

