/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.offscale.openfoodfacts.client.models

import io.offscale.openfoodfacts.client.models.Panel

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Knowledge panels for the tag
 *
 * @param additionalProperties 
 */

@Serializable
data class Panels1 (

    @SerialName("additionalProperties")
    val additionalProperties: Panel? = null

) {


}

